services:
  - type: web
    name: crypto-wallet-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wallet_tracker_bot.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ETHEREUM_RPC_URL
        sync: false
      - key: BASE_RPC_URL
        sync: false
      - key: ETHEREUM_WALLETS
        sync: false
      - key: BASE_WALLETS
        sync: false
